export const ocrResponseData = {
  data: {
    _id: '699210ff4d0a0eb4291aefee',
    request_id: 'bcvbvcvcb',
    filename: '04679fab-edb0-4631-bf7f-e1bc3973e2a1.pdf',
    s3_key_pdf: 'auditors-report/docs/04679fab-edb0-4631-bf7f-e1bc3973e2a1.pdf.pdf',
    ocr_extraction: {
      textract_job_id: 'ebfb3b829696ed4b4f806dd72d1b5db56517a26075a934de8241055feedd6022',
      ocr_text_key: 'auditors-report/docs/699210ff4d0a0eb4291aefee.ocr.txt',
      language_tag: 'LANG_EN',
      page_count: 1,
      is_readable: true,
      readability_score: 0.7176805970149253,
      status: 'SUCCEEDED',
      error: null,
      updated_at: '2026-02-15T18:31:35.496000',
      presigned_ocr_text_url:
        'https://cf-digitization-dev.s3.amazonaws.com/auditors-report/docs/699210ff4d0a0eb4291aefee.ocr.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAYMBHWUBN5KGTKY2E%2F20260215%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20260215T183135Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=73bc6e49abbc438fdbf4289ae318cce310cf4bc51af2cb5b00ea9266ed8d63b5',
    },
    classification: {
      doc_type: 'FULL_AUDIT_REPORT',
      confidence: 1,
      method: 'ai',
      evidence: [
        'Sub: Audit - Ramanathapuram District - Abiramam (Gr 1) TownPanchayat- Audit on the accounts for the year 2020 - 2021 - Issue of Audit Report - reg.',
        'The Audit Report mentioning the defects and irregularities are hereby issued for your perusal.',
        'As per the GO ref 3, the replies to the objections should be sent to this office with the approval of Town Panchayat council within two months on receipt of this Audit Report in three copies.',
      ],
      reason:
        "The document explicitly states its subject is the 'Issue of Audit Report' and refers to itself multiple times as 'this Audit Report', which mentions 'defects and irregularities'.",
      status: 'SUCCEEDED',
      error: null,
      updated_at: '2026-02-15T18:31:40.035000',
    },
    audit: {
      extraction: {
        audit_firm: 'Local Fund Audit',
        auditor_name: 'Mrs. S. Selvi, Assistant Director',
        audit_date: '04.02.2022',
        audit_place: 'Ramanathapuram',
        evidence_quotes: [
          'LOCAL FUND AUDIT DEPARTMENT',
          'From Mrs. S. Selvi, Assistant Director, Local Fund Audit, Ramanathapuram.',
          'R.C.No.38/A1/2022 Dated: 04.02.2022.',
          'Assistant Director, Local Fund Audit, Ramanathapuram.',
        ],
        method: 'ai',
        confidence: 0.7,
      },
      verification: {
        audit_firm: {
          value: 'Local Fund Audit',
          verified: true,
          match_type: 'direct',
        },
        auditor_name: {
          value: 'Mrs. S. Selvi, Assistant Director',
          verified: false,
          match_type: 'none',
        },
        audit_date: {
          value: '04.02.2022',
          verified: true,
          match_type: 'direct',
        },
        audit_place: {
          value: 'Ramanathapuram',
          verified: true,
          match_type: 'direct',
        },
      },
      verification_status: 'UNVERIFIED',
      status: 'SUCCEEDED',
      error: null,
      updated_at: '2026-02-15T18:31:45.906000',
    },
    summary: {
      data: {
        bullets: [
          'An audit of the Abiramam (Gr 1) Town Panchayat accounts for the year 2020-2021 has been completed.',
          'The audit was conducted by the Local Fund Audit Department, Ramanathapuram.',
          'An Audit Report detailing defects and irregularities has been issued.',
          'The Executive Officer must send replies to the objections within two months of receiving the report.',
          'Replies require approval from the Town Panchayat council and should be submitted in three copies.',
          'The audit was performed according to specific Government Orders and the Tamil Nadu Municipalities Act 1920.',
          'Receipt of the audit report should be acknowledged.',
        ],
        key_sections_detected: [
          'Header Information',
          'Subject',
          'References',
          'Audit Completion Statement',
          'Audit Report Issuance',
          'Reply Instructions',
          'Acknowledgment Request',
          'Sign-off',
          'Copy Recipients',
        ],
        risks_or_issues: ['defects and irregularities'],
        evidence_quotes: [
          'Audit on the accounts for the year 2020 - 2021 - Issue of Audit Report - reg.',
          'the audit on the accounts of Abiramam (Gr 1) Town Panchayat for the year 2020 - 2021 has been preferred and completed.',
          'The Audit Report mentioning the defects and irregularities are hereby issued for your perusal.',
          'the replies to the objections should be sent to this office with the approval of Town Panchayat council within two months',
        ],
        model: 'gemini-2.5-flash',
        status: 'SUCCEEDED',
        updated_at: '2026-02-15T18:31:52.433000',
      },
      status: 'SUCCEEDED',
      error: null,
      updated_at: '2026-02-15T18:31:52.433000',
    },
    processing: {
      status: 'SUCCEEDED',
      created_at: '2026-02-15T18:31:27.411000',
      updated_at: '2026-02-15T18:31:52.434000',
    },
    created_at: '2026-02-15T18:31:27.411000',
    updated_at: '2026-02-15T18:31:52.434000',
  },
};
