export enum CONTEXT_TYPE {
  FORM_SUBMISSION = 'FORM_SUBMISSION',
  WEBINAR = 'WEBINAR',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  GENERAL = 'GENERAL',
}

export enum THREAD_PURPOSE {
  FORM_COMMUNICATION = 'FORM_COMMUNICATION',
  WEBINAR_DISCUSSION = 'WEBINAR_DISCUSSION',
  ANNOUNCEMENT_DISCUSSION = 'ANNOUNCEMENT_DISCUSSION',
  GENERAL_DISCUSSION = 'GENERAL_DISCUSSION',
}

export enum MESSAGE_VISIBILITY {
  EXTERNAL = 'EXTERNAL',
  INTERNAL_ULB = 'INTERNAL_ULB',
  INTERNAL_STATE = 'INTERNAL_STATE',
  INTERNAL_MOHUA = 'INTERNAL_MOHUA',
  SYSTEM = 'SYSTEM',
}

export enum THREAD_PERMISSION {
  READ = 'READ',
  REPLY = 'REPLY',
  INTERNAL_NOTE = 'INTERNAL_NOTE',
}

export enum THREAD_STATUS {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
}

/** Maps to Role enum values in the auth module */
export enum ORG_TYPE {
  ULB = 'ULB',
  STATE = 'STATE',
  MOHUA = 'MoHUA',
  ADMIN = 'ADMIN',
  PMU = 'PMU',
}
