export enum FORM_WORKFLOW_ACTION {
  SAVE_DRAFT = 'SAVE_DRAFT',
  SUBMIT = 'SUBMIT',
  RETURN_BY_STATE = 'RETURN_BY_STATE',
  APPROVE_BY_STATE = 'APPROVE_BY_STATE',
  RETURN_BY_MOHUA = 'RETURN_BY_MOHUA',
  ACKNOWLEDGE_BY_MOHUA = 'ACKNOWLEDGE_BY_MOHUA',
}

export enum NOTIFICATION_TYPE {
  FORM_SUBMITTED = 'FORM_SUBMITTED',
  FORM_RETURNED_BY_STATE = 'FORM_RETURNED_BY_STATE',
  FORM_APPROVED_BY_STATE = 'FORM_APPROVED_BY_STATE',
  FORM_RETURNED_BY_MOHUA = 'FORM_RETURNED_BY_MOHUA',
  FORM_ACKNOWLEDGED_BY_MOHUA = 'FORM_ACKNOWLEDGED_BY_MOHUA',
  NEW_MESSAGE = 'NEW_MESSAGE',
}
