// src/common/auth/roles.enum.ts
// roles for xvi financial commission module
export enum UserRole {
  ULB = 'ULB',
  ULB_EDITOR = 'ULB-EDITOR',
  ULB_VIEWER = 'ULB-VIEWER',

  STATE = 'STATE',
  STATE_EDITOR = 'STATE-EDITOR',
  STATE_VIEWER = 'STATE-VIEWER',

  ADMIN = 'ADMIN',
}

export enum Scope {
  ULB = 'ULB',
  STATE = 'STATE',
  ADMIN = 'ADMIN',
}

export enum AccessLevel {
  ADMIN = 'ADMIN',
  EDITOR = 'EDITOR',
  VIEWER = 'VIEWER',
}

export enum Permission {
  // Common read
  VIEW_STATUS_REPORTS = 'VIEW_STATUS_REPORTS',
  VIEW_DASHBOARDS = 'VIEW_DASHBOARDS',

  // ULB actions
  UPLOAD_DOCUMENTS = 'UPLOAD_DOCUMENTS',
  MESSAGE_USERS = 'MESSAGE_USERS',
  FINAL_SUBMIT_TO_STATE_DMA = 'FINAL_SUBMIT_TO_STATE_DMA',

  // STATE actions
  UPLOAD_STATE_LEVEL_DOCUMENTS = 'UPLOAD_STATE_LEVEL_DOCUMENTS',
  REVIEW_ULB_SUBMISSIONS = 'REVIEW_ULB_SUBMISSIONS',
  APPROVE_ULB_SUBMISSIONS = 'APPROVE_ULB_SUBMISSIONS',
  PREPARE_GRANT_LETTERS = 'PREPARE_GRANT_LETTERS',
  RECOMMEND_EXEMPTIONS = 'RECOMMEND_EXEMPTIONS',
  FINAL_SUBMIT_TO_MOHUA = 'FINAL_SUBMIT_TO_MOHUA',

  // User management
  MANAGE_USERS = 'MANAGE_USERS',
  VIEW_MANAGED_USERS = 'VIEW_MANAGED_USERS',
  CREATE_MANAGED_USER = 'CREATE_MANAGED_USER',
  UPDATE_MANAGED_USER = 'UPDATE_MANAGED_USER',
  DELETE_MANAGED_USER = 'DELETE_MANAGED_USER',
}
