import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { ClientSession, Model, Types } from 'mongoose';
import { MESSAGE_VISIBILITY } from '../../common/constants/communication.constants';
import { IAuthUser } from '../../common/interfaces/auth-user.interface';
import { CommunicationPermissions } from '../../common/services/communication.permissions';
import { ISendMessageOptions } from '../../common/types/workflow.types';
import { Role } from '../../module/auth/enum/role.enum';
import { IMessage } from '../interfaces/message.interface';
import { IThreadReadState } from '../interfaces/thread-read-state.interface';
import { Message, MessageDocument } from '../schemas/message.schema';
import { ThreadReadState, ThreadReadStateDocument } from '../schemas/thread-read-state.schema';
import { MessageThreadService } from './message-thread.service';
import { ThreadParticipantService } from './thread-participant.service';

@Injectable()
export class MessageService {
  constructor(
    @InjectModel(Message.name)
    private readonly messageModel: Model<MessageDocument>,
    @InjectModel(ThreadReadState.name)
    private readonly readStateModel: Model<ThreadReadStateDocument>,
    private readonly threadService: MessageThreadService,
    private readonly participantService: ThreadParticipantService,
    private readonly communicationPermissions: CommunicationPermissions,
  ) {}

  /**
   * Sends a message to a thread, enforces reply permissions, and updates thread metadata.
   * System-generated messages bypass the reply permission check.
   * @param options Message payload including threadId, body, visibility, and senderUser.
   * @param session Optional MongoDB transaction session.
   * @returns Created message document.
   */
  async sendMessageToThread(
    options: ISendMessageOptions & { senderUser: IAuthUser },
    session?: ClientSession,
  ): Promise<IMessage> {
    const { threadId, senderUser, body } = options;

    const thread = await this.threadService.getThreadDetails(threadId, senderUser, session);
    const participants = await this.participantService.getThreadParticipants(threadId, session);

    if (!options.isSystemGenerated) {
      this.communicationPermissions.assertCanReplyToThread(senderUser, thread, participants);
    }

    const visibility = options.visibility ?? MESSAGE_VISIBILITY.EXTERNAL;

    const messageDoc = {
      threadId: new Types.ObjectId(threadId),
      contextType: thread.contextType,
      contextId: thread.contextId,
      senderId: new Types.ObjectId(senderUser._id),
      senderOrgType: senderUser.role as string,
      senderOrgId: this.resolveOrgId(senderUser),
      senderRoleCode: senderUser.role as string,
      body,
      attachments: options.attachments ?? [],
      visibility,
      parentMessageId: options.parentMessageId ? new Types.ObjectId(options.parentMessageId) : undefined,
      isSystemGenerated: options.isSystemGenerated ?? false,
      messageType: 'TEXT',
    };

    const insertOptions: { session?: ClientSession } = session ? { session } : {};
    const [message] = await this.messageModel.create([messageDoc], insertOptions);

    await this.threadService.updateThreadLastMessage(threadId, body, session);

    return message as unknown as IMessage;
  }

  /**
   * Creates a workflow-triggered message without checking CommunicationPermissions.
   * Use for messages generated by form workflow actions (return, approve, acknowledge)
   * where FormWorkflowPermissions has already been verified by the caller.
   * For user-initiated messages from the API use sendMessageToThread() instead.
   * @param options Message payload including threadId, body, visibility, and senderUser.
   * @param session Optional MongoDB transaction session.
   * @returns Created message document.
   * @throws NotFoundException if the thread does not exist.
   */
  async sendWorkflowMessage(
    options: ISendMessageOptions & { senderUser: IAuthUser },
    session?: ClientSession,
  ): Promise<IMessage> {
    const { threadId, senderUser, body } = options;

    const thread = await this.threadService.findThreadById(threadId, session);
    if (!thread) throw new NotFoundException('Thread not found');

    const visibility = options.visibility ?? MESSAGE_VISIBILITY.EXTERNAL;

    const messageDoc = {
      threadId: new Types.ObjectId(threadId),
      contextType: thread.contextType,
      contextId: thread.contextId,
      senderId: new Types.ObjectId(senderUser._id),
      senderOrgType: senderUser.role as string,
      senderOrgId: this.resolveOrgId(senderUser),
      senderRoleCode: senderUser.role as string,
      body,
      attachments: options.attachments ?? [],
      visibility,
      parentMessageId: options.parentMessageId ? new Types.ObjectId(options.parentMessageId) : undefined,
      isSystemGenerated: options.isSystemGenerated ?? false,
      messageType: 'TEXT',
    };

    const insertOptions: { session?: ClientSession } = session ? { session } : {};
    const [message] = await this.messageModel.create([messageDoc], insertOptions);

    await this.threadService.updateThreadLastMessage(threadId, body, session);

    return message as unknown as IMessage;
  }

  /**
   * Fetches paginated thread messages filtered by the user's visibility access level.
   * @param params.threadId Thread to fetch messages from.
   * @param params.user Authenticated user (determines which visibility levels are returned).
   * @param params.page Page number (1-indexed).
   * @param params.limit Messages per page.
   * @returns Paginated messages visible to the user, total count, and pagination echo.
   */
  async getThreadMessages(params: {
    threadId: string;
    user: IAuthUser;
    page: number;
    limit: number;
  }): Promise<{ messages: IMessage[]; total: number; page: number; limit: number }> {
    const { threadId, user, page, limit } = params;

    await this.threadService.getThreadDetails(threadId, user);

    const allowedVisibilities = this.getAllowedVisibilities(user);
    const filter = {
      threadId: new Types.ObjectId(threadId),
      visibility: { $in: allowedVisibilities },
    };

    const [records, total] = await Promise.all([
      this.messageModel
        .find(filter)
        .sort({ createdAt: 1 })
        .skip((page - 1) * limit)
        .limit(limit)
        .lean()
        .exec(),
      this.messageModel.countDocuments(filter).exec(),
    ]);

    return { messages: records as unknown as IMessage[], total, page, limit };
  }

  /**
   * Marks a thread as fully read for the user by resetting the unread count to zero (upsert).
   * @param threadId Thread to mark as read.
   * @param user Authenticated user whose read state to update.
   * @param session Optional MongoDB transaction session.
   */
  async markThreadAsRead(threadId: string, user: IAuthUser, session?: ClientSession): Promise<void> {
    const userId = new Types.ObjectId(user._id);
    const threadObjId = new Types.ObjectId(threadId);

    const updateOptions: { session?: ClientSession; upsert: boolean; new: boolean } = {
      upsert: true,
      new: true,
      ...(session ? { session } : {}),
    };

    await this.readStateModel
      .findOneAndUpdate({ threadId: threadObjId, userId }, { lastReadAt: new Date(), unreadCount: 0 }, updateOptions)
      .exec();
  }

  /**
   * Returns the number of unread messages in a thread for the user.
   * Falls back to counting all visible messages if no read-state record exists yet.
   * @param threadId Thread to check.
   * @param user Authenticated user.
   * @returns Unread message count visible to the user.
   */
  async getUnreadCount(threadId: string, user: IAuthUser): Promise<number> {
    const state = await this.readStateModel
      .findOne({
        threadId: new Types.ObjectId(threadId),
        userId: new Types.ObjectId(user._id),
      })
      .lean()
      .exec();

    if (!state) {
      const allowedVisibilities = this.getAllowedVisibilities(user);
      return this.messageModel
        .countDocuments({
          threadId: new Types.ObjectId(threadId),
          visibility: { $in: allowedVisibilities },
        })
        .exec();
    }

    return (state as unknown as IThreadReadState).unreadCount ?? 0;
  }

  private getAllowedVisibilities(user: IAuthUser): string[] {
    const base: string[] = [MESSAGE_VISIBILITY.EXTERNAL, MESSAGE_VISIBILITY.SYSTEM];
    if (user.role === Role.MoHUA || user.role === Role.ADMIN) {
      return [
        ...base,
        MESSAGE_VISIBILITY.INTERNAL_MOHUA,
        MESSAGE_VISIBILITY.INTERNAL_STATE,
        MESSAGE_VISIBILITY.INTERNAL_ULB,
      ];
    }
    if (user.role === Role.STATE) return [...base, MESSAGE_VISIBILITY.INTERNAL_STATE];
    if (user.role === Role.ULB) return [...base, MESSAGE_VISIBILITY.INTERNAL_ULB];
    return base;
  }

  private resolveOrgId(user: IAuthUser): Types.ObjectId | undefined {
    if (user.ulb) return new Types.ObjectId(user.ulb);
    if (user.state) return new Types.ObjectId(user.state);
    return undefined;
  }
}
